# CH 11 - Polarization

In [40]:
import numpy as np
from numpy import sin, cos, pi, tan, exp, sqrt

## Jones Calculus: Polarizers
- **Example 11.1**: Use Jones calculus to calculate the mergent beam from a series of optical polarizers.

In [7]:
# incident beam
Ei = np.array([[1],[0]])

# polarizer types; linear polarizer at angle theta to the x-axis
theta = pi/4
Lphi = np.array([       
    [cos(theta)**2, cos(theta)*sin(theta)],
    [cos(theta)*sin(theta), sin(theta)**2]
])

In [12]:
# emergent beam from polarizers
Eo = np.dot(Lphi, Ei)
Eo

array([[0.5],
       [0.5]])

## Jones Calculus: Phase Retarders
- **Example 11.2**: Convert a linearly polarized beam into a circularly polarized beam using a quarter-wave plate.

In [43]:
# incident beam
Ei = np.array([[1], [0]])

# polarizer types
phi = pi/4
QWP = exp(1j * pi/4) * np.array([
    [cos(phi)**2 - 1j*sin(phi)**2, cos(phi)*sin(phi)*(1+1j)],
    [cos(phi)*sin(phi)*(1+1j), -1j*cos(phi)**2 + sin(phi)**2]
])
      
# emergent beam
Eo = np.dot(QWP, Ei)
Eo

array([[7.07106781e-01+5.55111512e-17j],
       [5.55111512e-17+7.07106781e-01j]])

## Mueller Calculus
- **Example 11.3**: Apply a linear polarizer to a Stokes vector to convert from X polarization to Y polarization.

In [47]:
# incident beam
Si = np.array([[1],
               [1],
               [0],
               [0]])

# polarizer types
phi = pi/4
A = cos(2*phi)
B= sin(2*phi)

LP = 0.5 * np.array([
    [1, A,    B,    0],
    [A, A**2, A*B,  0],
    [B, A*B,  B**2, 0],
    [0, 0,    0,    0]
])

# emergent beam
S = np.dot(LP, Si)
S

array([[5.000000e-01],
       [3.061617e-17],
       [5.000000e-01],
       [0.000000e+00]])